default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['postgresql_username'] %>
  password: <%= ENV['postgresql_password'] %>
  pool: 5

development:
  <<: *default
  database: jeremic-marketplace_development

test:
  <<: *default
  database: jeremic-marketplace_test

production:
  <<: *default
  database: jeremic-marketplace_production
  username: jeremic-marketplace
  password: <%= ENV['JEREMIC-MARKETPLACE_DATABASE_PASSWORD'] %>
